version: '3.8'

services:
  flask-docker-api:
    container_name: inethi-updater
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/app
    network_mode: "host"
    cap_add:
      - NET_RAW
      - NET_ADMIN