version: "3"
services:
  inethi-updater-frontend:
    build: .
    container_name: inethi-updater-frontend
    ports:
      - '3000:3000'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.updaterFrontend.rule=Host(`maintain.inethilocal.net`)"
      - "traefik.http.routers.updaterFrontend.entrypoints=websecure"
networks:
  default:
    external:
      name: "inethi-bridge-traefik"