version: '3'

services:
  inethi-user-management-api:
    container_name: inethi-user-management-api
    build: .
    restart: unless-stopped
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - inethi-user-management-mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`usermanagement.inethilocal.net`)"
      - "traefik.http.routers.django.entrypoints=websecure"
    volumes:
      - '/mnt/data/inethi_user_management/app:/home/app/webapp'
    ports:
      - "8000:8000"
  inethi-user-management-mysql:
    container_name: inethi-user-management-mysql
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'inethi-user-management-api'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - '/mnt/data/inethi_user_management_mysql:/var/lib/mysql'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.djangomysql.entrypoints=websecure"

volumes:
  inethi_user_management_data:
networks:
  default:
    external:
      name: "inethi-bridge-traefik"
