version: '3'
services:

  radiusdesk:
    build:
      context: ./
      dockerfile: Dockerfile-build-radiusdesk
      args:
        radiusdesk_volume: ${RADIUSDESK_VOLUME}
    container_name: inethi-radiusdesk

    environment:
      - "PHP_INI_SCAN_DIR=:/p/gd"
      - "PHP.cgi.fix_pathinfo=1"
      - "PHP_SELF=/index.php"
    restart: always

    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.radiusdesk.rule=Host(`${TRAEFIK_API_RULE_HOST}.${inethiDN}`)"
        - "traefik.http.routers.radiusdesk.entrypoints=${TRAEFIK_ENTRYPOINT}"

    depends_on:
      - "rdmariadb"

    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"

  rdmariadb:
    container_name: inethi-radiusdesk-mariadb
    image: docker.io/bitnami/mariadb:10.5

    restart: always
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
      - "MARIADB_USER=rd"
      - "MARIADB_DATABASE=rd"
      - "MARDIADB_PASSWORD=rd"

    volumes:
      - ${RADIUSDESK_VOLUME}/db_conf/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
      - rd_data:/bitnami/mariadb
      - ${RADIUSDESK_VOLUME}/db_startup:/tmp

volumes:
  rd_data:


networks:
  default:
    external:
      name: "${INETHI_NETWORK}"




