- name: Deploy Jellyfin with Docker Container
  hosts: localserver
  become: true
  gather_facts: no

  vars:
    NEXTCLOUD_RSHARE_VOLUME: "/mnt/data/Rshare"
    NEXTCLOUD_RVIDEO_VOLUME: "/mnt/data/Rvideo"
    NEXTCLOUD_RPHOTO_VOLUME: "/mnt/data/Rphoto"
    NEXTCLOUD_RMUSIC_VOLUME: "/mnt/data/Rmusic"
    JELLYFIN_VOLUME: "/mnt/data/jellyfin"
    TRAEFIK_API_RULE_HOST: "jellyfin"
    inethi_dn: "inethilocal.net"
    TRAEFIK_ENTRYPOINT: "websecure"
    INETHI_NETWORK: "inethi-bridge-traefik"

  tasks:
    - name: Start Jellyfin container
      docker_container:
        name: inethi-jellyfin
        image: linuxserver/jellyfin
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "UTC"
          UMASK_SET: "022"
        volumes:
          - "{{ NEXTCLOUD_RSHARE_VOLUME }}:/mnt/Rshare"
          - "{{ NEXTCLOUD_RVIDEO_VOLUME }}:/mnt/Rvideo"
          - "{{ NEXTCLOUD_RPHOTO_VOLUME }}:/mnt/Rphoto"
          - "{{ NEXTCLOUD_RMUSIC_VOLUME }}:/mnt/Rmusic"
          - "{{ JELLYFIN_VOLUME }}/config:/config"
        restart_policy: unless-stopped
        labels:
          traefik.enable: "true"
          traefik.http.routers.jellyfin.rule: "Host(`{{ TRAEFIK_API_RULE_HOST }}.{{ inethi_dn }}`)"
          traefik.http.routers.jellyfin.entrypoints: "{{ TRAEFIK_ENTRYPOINT }}"
        networks:
          - name: "{{ INETHI_NETWORK }}"
