- name: Deploy Nextcloud stack
  hosts: localserver
  become: true
  gather_facts: no
  vars:
    mysql_root_password: "iNethi2023#"
    mysql_password: "iNethi2023#"
    nextcloud_volume: "/mnt/data/nextcloud"
    mysql_volume: "/mnt/data/nextcloud-mysql"
    nextcloud_rshare_volume: "/mnt/data/Rshare"
    nextcloud_rvideo_volume: "/mnt/data/Rvideo"
    nextcloud_rphoto_volume: "/mnt/data/Rphoto"
    nextcloud_rmusic_volume: "/mnt/data/Rmusic"
    traefik_api_rule_nextcloud: "nextcloud"
    inethi_dn: "inethilocal.net"
    traefik_entrypoint: "websecure"
    INETHI_NETWORK: "inethi-bridge-traefik"

  tasks:
    - name: Start MySQL container for Nextcloud
      docker_container:
        name: inethi-nextcloud-mysql
        image: mysql:latest
        command: "--transaction-isolation=READ-COMMITTED --binlog-format=ROW"
        env:
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
          MYSQL_PASSWORD: "{{ mysql_password }}"
          MYSQL_DATABASE: "inethi_nextcloud"
          MYSQL_USER: "inethi"
        volumes:
          - "{{ mysql_volume }}:/var/lib/mysql"
        restart_policy: unless-stopped
        networks:
          - name: "{{ INETHI_NETWORK }}"

    - name: Start Nextcloud container
      docker_container:
        name: inethi-nextcloud
        image: nextcloud
        links:
          - "inethi-nextcloud-mysql:mysql"
        volumes:
          - "{{ nextcloud_volume }}:/var/www/html"
          - "{{ nextcloud_rshare_volume }}:/mnt/Rshare"
          - "{{ nextcloud_rvideo_volume }}:/mnt/Rvideo"
          - "{{ nextcloud_rphoto_volume }}:/mnt/Rphoto"
          - "{{ nextcloud_rmusic_volume }}:/mnt/Rmusic"
        labels:
          traefik.enable: "true"
          traefik.http.routers.nextcloud.rule: "Host(`{{ traefik_api_rule_nextcloud }}.{{ inethi_dn }}`)"
          traefik.http.routers.nextcloud.entrypoints: "{{ traefik_entrypoint }}"
        restart_policy: unless-stopped
        networks:
          - name: "{{ INETHI_NETWORK }}"



