- name: Deploy Radiusdesk with Docker Container
  hosts: localserver
  become: true
  gather_facts: yes

  vars:
    TRAEFIK_API_RULE_HOST: "radiusdesk"
    inethi_dn: "inethilocal.net"
    TRAEFIK_ENTRYPOINT: "websecure"
    INETHI_NETWORK: "inethi-bridge-traefik"
    RADIUSDESK_VOLUME: "/mnt/data/radius_desk"

  tasks:
    - name: Create Docker volume
      docker_volume:
        name: rd_data

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0777'
      with_items:
        - "{{ RADIUSDESK_VOLUME }}"
        - "{{ RADIUSDESK_VOLUME }}/db_startup"
        - "{{ RADIUSDESK_VOLUME }}/db_conf"

    - name: Copy files to Server
      copy:
        src: "{{ playbook_dir }}/radius_desk/"
        dest: "{{ RADIUSDESK_VOLUME }}"

    - name: Clone rdcore git repository
      git:
        repo: "https://github.com/iNethi/rdcore.git"
        dest: "/mnt/data/rdcore"
        clone: yes

    - name: Copy database setup files
      copy:
        src: "{{ item }}"
        dest: "{{ RADIUSDESK_VOLUME }}/db_startup/"
        remote_src: yes
      with_items:
        - "/mnt/data/rdcore/cake3/rd_cake/setup/db/rd.sql"
        - "{{ RADIUSDESK_VOLUME }}/db_priveleges.sql"
        - "{{ RADIUSDESK_VOLUME }}/startup.sh"

    - name: Copy my_custom.cnf file
      copy:
        src: "{{ RADIUSDESK_VOLUME }}/my_custom.cnf"
        dest: "{{ RADIUSDESK_VOLUME }}/db_conf/"
        remote_src: yes

    - name: Remove rdcore repository
      file:
        path: "/mnt/data/rdcore"
        state: absent

    - name: Build RadiusDesk Database
      command: "docker-compose -f /mnt/data/radius_desk/docker-compose.yml up -d rdmariadb"

    - name: Set permissions on startup.sh
      file:
        path: "{{ RADIUSDESK_VOLUME }}/db_startup/startup.sh"
        mode: '0777'

    - name: Create Database for RadiusDesk
      shell: "docker exec -u 0 -it inethi-radiusdesk-mariadb /tmp/startup.sh"

    - name: Build RadiusDesk
      command: "docker-compose -f /mnt/data/radius_desk/docker-compose.yml build"

    - name: Run RadiusDesk
      command: "docker-compose -f /mnt/data/radius_desk/docker-compose.yml up -d radiusdesk"

