- name: Deploy Wordpress stack
  hosts: localserver
  become: true
  gather_facts: no
  vars_files:
    - ../config.yml
  vars:
    WORDPRESS_MOUNT: "/mnt/data/wordpress"
    WORDPRESS_DB_NAME: "wordpress"
    WORDPRESS_TABLE_PREFIX: "wp_"
    WORDPRESS_DB_HOST: "inethi-wordpress-mariadb"
    WORDPRESS_DB_USER: "inethi"
    WORDPRESS_DB_PASSWORD: "iNethi2023#"
    MARIADB_MOUNT: "/mnt/data/wordpress-mariadb"
    MYSQL_ROOT_PASSWORD: "iNethi2023#"
    TRAEFIK_API_RULE_WORDPRESS: "wordpress"
    inethiDN: "inethilocal.net"
    TRAEFIK_ENTRYPOINT: "websecure"
    INETHI_NETWORK: "inethi-bridge-traefik"

  tasks:
    - name: Deploy MariaDB
      docker_container:
        name: inethi-wordpress-mariadb
        image: mariadb:latest
        state: started
        restart_policy: unless-stopped
        env:
          MYSQL_ROOT_PASSWORD: "{{ CONF_MASTER_PASSWORD }}"
          MYSQL_USER: "{{ WORDPRESS_DB_USER }}"
          MYSQL_PASSWORD: "{{ CONF_MASTER_PASSWORD }}"
          MYSQL_DATABASE: "{{ WORDPRESS_DB_NAME }}"
        volumes:
          - "{{ MARIADB_MOUNT }}:/var/lib/mysql"
        networks:
          - name: "{{ INETHI_NETWORK }}"

    - name: Deploy WordPress
      docker_container:
        name: inethi-wordpress
        image: wordpress:latest
        state: started
        restart_policy: unless-stopped
        env:
          WORDPRESS_DB_NAME: "{{ WORDPRESS_DB_NAME }}"
          WORDPRESS_TABLE_PREFIX: "{{ WORDPRESS_TABLE_PREFIX }}"
          WORDPRESS_DB_HOST: "{{ WORDPRESS_DB_HOST }}"
          WORDPRESS_DB_USER: "{{ WORDPRESS_DB_USER }}"
          WORDPRESS_DB_PASSWORD: "{{ CONF_MASTER_PASSWORD }}"
        volumes:
          - "{{ WORDPRESS_MOUNT }}:/var/www/html"
        labels:
          traefik.enable: "true"
          traefik.http.routers.wordpress.rule: "Host(`{{ TRAEFIK_API_RULE_WORDPRESS }}.{{ inethiDN }}`)"
          traefik.http.routers.wordpress.entrypoints: "{{ TRAEFIK_ENTRYPOINT }}"
        links:
          - "inethi-wordpress-mariadb:inethi-wordpress-mariadb-alias"
        networks:
          - name: "{{ INETHI_NETWORK }}"
